/**
 * The seven excavation questions, and the twenty example beliefs for each
 * one, taken from "The Seven Excavation Questions" appendix.
 */

var QUESTION_TEXT = [
  "What am I believing about myself today that isn't true?",
  "What am I believing about donors that creates scarcity?",
  "What am I believing about time that keeps me trapped?",
  "What am I believing about money that creates anxiety?",
  "What truth do I need to remember right now?",
  "Who am I becoming through this work?",
  "What's one belief I'm choosing to practice today?"
];

var SAMPLE_ANSWERS = {
  1: [
    "I'm believing I have to prove my worth through results today. That's not true. My worth isn't dependent on outcomes.",
    "I'm believing I'm behind everyone else my age. Comparison is a lie. I'm exactly where my journey has brought me.",
    "I'm believing that if I rest, I'm lazy. Rest is stewardship, not weakness.",
    "I'm believing I don't belong in rooms with bigger leaders. I was invited because I bring something.",
    "I'm believing yesterday's mistake defines today. It doesn't. Today is new.",
    "I'm believing I have to have all the answers before I speak. Leaders learn out loud.",
    "I'm believing I'm an impostor who will be found out. My track record says otherwise.",
    "I'm believing I'm only as good as my last campaign. My identity isn't a metric.",
    "I'm believing that saying no makes me selfish. Saying no protects what I said yes to.",
    "I'm believing I'm too old to change how I lead. Growth has no expiration date.",
    "I'm believing that asking for help means I'm failing. Asking for help is how strong leaders stay strong.",
    "I'm believing I need everyone's approval to move forward. I need clarity, not consensus.",
    "I'm believing my sensitivity is a liability. It's the source of my empathy and my best decisions.",
    "I'm believing I have to carry this organization alone. I was never meant to carry it alone.",
    "I'm believing that if I'm not exhausted, I'm not committed. Exhaustion isn't devotion.",
    "I'm believing I'm not a 'real' fundraiser. I invite people into meaningful work — that's the realest kind.",
    "I'm believing my quiet leadership style isn't enough. Presence doesn't require volume.",
    "I'm believing one critical email means I'm failing at everything. One voice is not the verdict.",
    "I'm believing I should be further along by now. Faithfulness is measured in seasons, not sprints.",
    "I'm believing I can't be a good leader and a good parent at the same time. That's a false choice."
  ],
  2: [
    "I'm believing that if I don't respond to this donor immediately, they'll give to someone else. That's scarcity thinking. Aligned donors respect boundaries.",
    "I'm believing donors are doing me a favor. They're investing in a mission they believe in — it's a partnership.",
    "I'm believing I can't ask again this year. Generous people want to give; my job is to invite, not decide for them.",
    "I'm believing this one major donor holds our future. No single person is our source.",
    "I'm believing donors will leave if I show any weakness. Honesty deepens trust; performance erodes it.",
    "I'm believing I have to say yes to every donor request. Mission drives strategy, not donor preferences.",
    "I'm believing there aren't enough donors who care about our cause. There are more aligned people than I've ever met.",
    "I'm believing the ask will damage the relationship. A clear ask honors the relationship.",
    "I'm believing I have to entertain donors to keep them. They stay for impact, not performance.",
    "I'm believing a 'no' means the relationship is over. A no is information, not rejection.",
    "I'm believing donors only care about overhead ratios. Donors care about transformation, and I can tell that story.",
    "I'm believing I need to apologize when I ask for money. I'm offering an opportunity, not begging.",
    "I'm believing lapsed donors are lost forever. They're one honest conversation away from returning.",
    "I'm believing that if the economy is down, giving is impossible. People give through every economy when the vision is clear.",
    "I'm believing I have to compete with bigger organizations. Our donors aren't a market share — they're a community.",
    "I'm believing this donor's silence means they're upset. Silence usually means they're busy.",
    "I'm believing I must accept every gift, even ones with strings that pull us off mission. Some gifts cost more than they give.",
    "I'm believing donors want constant contact or they'll forget us. Donors want meaningful contact, not frequent contact.",
    "I'm believing that fundraising is taking. Fundraising is connecting generosity to purpose.",
    "I'm believing I'm bothering people when I follow up. Follow-up is service — it finishes what the donor started caring about."
  ],
  3: [
    "I'm believing there's never enough time. But that's not true. There's always enough time for what matters most when I'm strategic.",
    "I'm believing I have to answer every message today. Almost nothing is actually urgent.",
    "I'm believing busy equals productive. Busy is often just avoidance with a calendar.",
    "I'm believing my deep-work block is negotiable. It's the most important meeting on my schedule.",
    "I'm believing I'll have more time next month. Next month has the same 24 hours — I have to choose now.",
    "I'm believing that if I slow down, everything falls apart. The organization outlasted my last vacation.",
    "I'm believing I can't say no to a meeting request. Every yes to a meeting is a no to something else.",
    "I'm believing I'm the only one who can do this task. Delegation is development, not dumping.",
    "I'm believing margin is a luxury for later. Margin is the fuel for everything else.",
    "I'm believing I lost the morning, so the day is wasted. The next hour is always available.",
    "I'm believing speed is the same as progress. Direction matters more than pace.",
    "I'm believing I have to be available to everyone at all times. Availability isn't the same as faithfulness.",
    "I'm believing planning time is wasted time. An hour of planning saves a week of scrambling.",
    "I'm believing I'm behind on some invisible schedule. Whose schedule? The work has its own season.",
    "I'm believing that rest steals time from the mission. Rest is what makes me useful to the mission.",
    "I'm believing multitasking gets more done. It just does more things badly.",
    "I'm believing my calendar controls me. I built the calendar; I can rebuild it.",
    "I'm believing this season of overwhelm is permanent. Seasons end — that's what makes them seasons.",
    "I'm believing I don't have time to think. Thinking is the job; everything else is the overflow.",
    "I'm believing that if it's not done today, it never will be. Consistent small steps finish what heroic sprints abandon."
  ],
  4: [
    "I'm believing we won't make budget unless I say yes to everything. But that's the hustle fallacy. Strategic focus raises more than scattered effort.",
    "I'm believing this shortfall means the mission is dying. A gap is a problem to solve, not a prophecy.",
    "I'm believing money is scarce. Generosity in this country dwarfs our budget — alignment is the work, not scarcity.",
    "I'm believing I have to personally close every gap. The board, the team, and the community carry this with me.",
    "I'm believing that talking about money is unspiritual. Money is a tool for mission, and clarity about it is holy work.",
    "I'm believing a reserve fund means we lack faith. A reserve fund means we can say yes when opportunity comes.",
    "I'm believing we can't invest in fundraising until we have more money. That's like refusing to plant until after the harvest.",
    "I'm believing one bad quarter defines our trajectory. Trends matter; single data points don't.",
    "I'm believing I should feel guilty about my salary. A sustainable leader is part of a sustainable mission.",
    "I'm believing that cutting everything is the only responsible move. Sometimes the responsible move is investing in growth.",
    "I'm believing wealthy people won't understand our work. Wealth doesn't erase heart — some of our best champions have both.",
    "I'm believing we have to grow the budget every year to be legitimate. Faithfulness, not size, is the measure.",
    "I'm believing this grant rejection means the funders see something wrong with us. Rejections are usually about fit and timing.",
    "I'm believing I have to hide financial challenges from the team. Transparency builds owners; secrecy builds spectators.",
    "I'm believing money problems are character problems. They're math problems with emotional weight.",
    "I'm believing we can't afford good tools, good people, or good counsel. We can't afford cheap versions of things that matter.",
    "I'm believing the year-end appeal will fail like I fear it will. Fear is not a forecast.",
    "I'm believing I need to check the bank balance five times a day. Watching the pot doesn't fill it — working the plan does.",
    "I'm believing that asking board members to give is overstepping. Board giving is board leading.",
    "I'm believing financial pressure means God has abandoned this work. Pressure is not abandonment; provision often arrives through the process."
  ],
  5: [
    "I am enough. The mission is resourced. God is faithful. My job is faithfulness, not control.",
    "The work matters even on the days I can't see the results.",
    "I was called to this — the difficulty doesn't cancel the calling.",
    "People are more forgiving than my anxiety tells me they are.",
    "The organization survived before me and grows through me — it doesn't rest solely on me.",
    "One conversation at a time is how everything important gets built.",
    "My team is capable. Trusting them is not a risk; it's the plan.",
    "Provision has come through every season so far, including the ones that looked impossible.",
    "I can do hard things slowly. Slow is not the same as stuck.",
    "The donors who are meant to partner with us will recognize the vision.",
    "My value was settled before I ever raised a dollar.",
    "Clarity is kindness — to my team, my donors, and myself.",
    "I don't have to feel confident to act faithfully.",
    "The people we serve are worth every uncomfortable ask.",
    "Peace is not the absence of problems; it's the presence of perspective.",
    "I have navigated every crisis to date with a 100 percent survival rate.",
    "God's timing has been better than my deadlines, every single time.",
    "Small faithful steps compound into things I can't yet imagine.",
    "I am allowed to be a person, not just a position.",
    "The mission is bigger than this moment, and this moment will pass."
  ],
  6: [
    "I'm becoming someone who operates from abundance instead of scarcity. Someone who's magnetic instead of desperate. Someone who's fully alive while doing work that matters.",
    "I'm becoming a leader who asks boldly because I believe deeply.",
    "I'm becoming someone who can sit with uncertainty without being ruled by it.",
    "I'm becoming a person whose calendar reflects their convictions.",
    "I'm becoming someone who develops leaders instead of collecting tasks.",
    "I'm becoming a storyteller who lets the mission speak louder than my insecurity.",
    "I'm becoming someone who receives generosity without shrinking from it.",
    "I'm becoming a leader who rests without guilt and works without frenzy.",
    "I'm becoming someone whose peace doesn't depend on the balance sheet.",
    "I'm becoming a person who says the true thing kindly instead of the safe thing quietly.",
    "I'm becoming someone who celebrates progress instead of only auditing gaps.",
    "I'm becoming a leader my younger self would have needed.",
    "I'm becoming someone who holds the mission with open hands instead of a clenched grip.",
    "I'm becoming a person of depth in a culture of hurry.",
    "I'm becoming someone who trusts the process on the days the process is invisible.",
    "I'm becoming a leader who invites partnership instead of performing self-sufficiency.",
    "I'm becoming someone whose identity is rooted deeper than any role.",
    "I'm becoming a person who chooses courage in small moments, not just big ones.",
    "I'm becoming someone who leaves people more hopeful than I found them.",
    "I'm becoming a steward, not an owner — and it's setting me free."
  ],
  7: [
    "Today I'm practicing the belief that boundaries with donors demonstrate respect, not apathy. I will protect my 90-minute block even when it feels uncomfortable.",
    "Today I'm practicing the belief that my worth isn't tied to today's results. I will end the day at 5:30 regardless of what's unfinished.",
    "Today I'm practicing the belief that asking is serving. I will make two donor calls without apologizing for either.",
    "Today I'm practicing the belief that my team is capable. I will delegate the report and not take it back.",
    "Today I'm practicing the belief that rest is productive. I will take a real lunch away from my desk.",
    "Today I'm practicing the belief that clarity is kindness. I will send the honest email instead of the vague one.",
    "Today I'm practicing the belief that there's enough time for what matters. I will do the most important thing first.",
    "Today I'm practicing the belief that a no is information, not rejection. I will follow up with the foundation that declined us.",
    "Today I'm practicing the belief that provision follows faithfulness. I will work the plan instead of refreshing the bank balance.",
    "Today I'm practicing the belief that I belong in the room. I will speak up in the board meeting without qualifying every sentence.",
    "Today I'm practicing the belief that slow progress is still progress. I will celebrate one small win out loud with my team.",
    "Today I'm practicing the belief that donors want to be invited. I will make the specific ask I've been softening for weeks.",
    "Today I'm practicing the belief that I don't have to be available to everyone instantly. I will check email three times, not thirty.",
    "Today I'm practicing the belief that transparency builds trust. I will share the real numbers with my leadership team.",
    "Today I'm practicing the belief that my presence matters more than my performance. I will be fully in the meeting I'm dreading.",
    "Today I'm practicing the belief that gratitude multiplies. I will write three thank-you notes before I open my inbox.",
    "Today I'm practicing the belief that saying no protects my yes. I will decline the committee request without over-explaining.",
    "Today I'm practicing the belief that fear is not a forecast. I will plan the year-end campaign from vision, not panic.",
    "Today I'm practicing the belief that I'm a steward, not the source. I will pray about the gap before I strategize about it.",
    "Today I'm practicing the belief that this work is a privilege. I will begin the day with thanks instead of a to-do list."
  ]
};
